-- 코드를 입력하세요
WITH TEMP_TABLE(CART_ID) AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)


SELECT ORIGIN.CART_ID
FROM CART_PRODUCTS ORIGIN
INNER JOIN TEMP_TABLE ON TEMP_TABLE.CART_ID = ORIGIN.CART_ID
WHERE ORIGIN.NAME = 'Yogurt'

ORDER BY CART_ID ASC