-- 코드를 작성해주세요
WITH RECURSIVE NEW_ECOLI_DATA AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, N.GENERATION+1
    FROM ECOLI_DATA E
    JOIN NEW_ECOLI_DATA N ON N.ID = E.PARENT_ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM NEW_ECOLI_DATA
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION ASC